CREATE TABLE login_attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password_h TEXT NOT NULL,
  password_s TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE code_attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  login_attempt_id INTEGER,
  username TEXT,
  code TEXT NOT NULL,
  code TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);